name: Keep Render Awake

on:
  schedule:
    - cron: '*/10 * * * *'  # Каждые 10 минут
  workflow_dispatch:  # Ручной запуск при необходимости

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render
        run: curl -s -o /dev/null https://valentine-bot.onrender.com/health